// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
	integrations: [
		starlight({
			title: '1UP Media Solutions SOPs',
			description: 'A starter wiki for a seven-figure agency — paid, organic, sales, ops, measurement, creative.',
			customCss: ['./src/styles/custom.css'],
			components: {
				Footer: './src/components/BuildFooter.astro',
				SiteTitle: './src/components/SiteTitleWithBuild.astro',
				PageTitle: './src/components/PageTitle.astro',
			},
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/ojhurst/7fa-sop-example',
				},
			],
			sidebar: [
				{ label: 'Home', slug: 'index' },
				{ label: 'Command Center', link: '/command-center' },
				{
					label: 'Paid Acquisition',
					items: [
						{ label: 'Google Ads — Search Campaign Setup', slug: 'paid-acquisition/google-ads-search-setup' },
						{ label: 'Google Ads — Performance Max Playbook', slug: 'paid-acquisition/google-ads-pmax' },
						{ label: 'Google Ads — Keyword Research Process', slug: 'paid-acquisition/google-ads-keyword-research' },
						{ label: 'Google Ads — Negative Keyword Hygiene', slug: 'paid-acquisition/google-ads-negatives' },
						{ label: 'Facebook Ads — Campaign Structure', slug: 'paid-acquisition/fb-ads-structure' },
						{ label: 'Facebook Ads — Creative Testing Framework', slug: 'paid-acquisition/fb-ads-creative-testing' },
						{ label: 'Facebook Ads — Audience Targeting Playbook', slug: 'paid-acquisition/fb-ads-audiences' },
						{ label: 'Facebook Ads — Conversions API Setup', slug: 'paid-acquisition/fb-ads-capi' },
						{ label: 'YouTube Ads — Video Ad Production', slug: 'paid-acquisition/youtube-ads-production' },
						{ label: 'Paid — Account Audit Process', slug: 'paid-acquisition/account-audit' },
						{ label: 'Paid — Pixel and CAPI Debugging', slug: 'paid-acquisition/pixel-debugging' },
						{ label: 'Paid — Scaling Rules and Budget Changes', slug: 'paid-acquisition/scaling-rules' },
						{ label: 'Paid — Landing Pages for Paid Traffic', slug: 'paid-acquisition/paid-landing-pages' },
						{ label: 'Paid — Agency Retargeting Funnel', slug: 'paid-acquisition/agency-retargeting' },
					],
				},
				{
					label: 'Organic Acquisition',
					items: [
						{ label: 'SEO — On-page Checklist', slug: 'organic/seo-onpage' },
						{ label: 'SEO — Content Pillar Strategy', slug: 'organic/seo-pillars' },
						{ label: 'Local SEO — Google Business Profile', slug: 'organic/local-seo-gbp' },
						{ label: 'Content — Blog Post Production SOP', slug: 'organic/blog-production' },
						{ label: 'Social — LinkedIn Content Cadence', slug: 'organic/linkedin-cadence' },
						{ label: 'Organic — Review Generation Playbook', slug: 'organic/review-generation' },
						{ label: 'Organic — Local Citations and Directory Listings', slug: 'organic/local-citations' },
						{ label: 'Organic — Email Newsletter Production', slug: 'organic/email-newsletter' },
						{ label: 'Organic — Backlink Outreach Process', slug: 'organic/backlink-outreach' },
						{ label: 'Organic — Authority Book and Lead Magnet', slug: 'organic/authority-book' },
						{ label: 'Organic — Niche Authority Positioning', slug: 'organic/niche-authority-positioning' },
					],
				},
				{
					label: 'Sales and Onboarding',
					items: [
						{ label: 'Sales — Discovery Call Framework', slug: 'sales-onboarding/discovery-call' },
						{ label: 'Sales — Proposal Template', slug: 'sales-onboarding/proposal-template' },
						{ label: 'Sales — Lead Qualification', slug: 'sales-onboarding/lead-qualification' },
						{ label: 'Sales — Follow-up Cadence', slug: 'sales-onboarding/followup-cadence' },
						{ label: 'Sales — Cold Outreach Playbook', slug: 'sales-onboarding/cold-outreach' },
						{ label: 'Sales — Demo Call Structure', slug: 'sales-onboarding/demo-call' },
						{ label: 'Sales — Pricing Conversation', slug: 'sales-onboarding/pricing-conversation' },
						{ label: 'Onboarding — Day 1 Kickoff', slug: 'sales-onboarding/onboarding-day-one' },
						{ label: 'Onboarding — Access Collection Checklist', slug: 'sales-onboarding/access-checklist' },
						{ label: 'Onboarding — Week 1 Strategy Deck', slug: 'sales-onboarding/week-one-strategy' },
						{ label: 'Client Management — Weekly Report Format', slug: 'sales-onboarding/weekly-report' },
						{ label: 'Client Management — Quarterly Business Review', slug: 'sales-onboarding/qbr' },
						{ label: 'Client Management — Renewals and Upsells', slug: 'sales-onboarding/renewals-upsells' },
					],
				},
				{
					label: 'Operations',
					items: [
						{ label: 'Client Management — Escalation Ladder', slug: 'operations/escalation-ladder' },
						{ label: 'Client Offboarding — Graceful Exit', slug: 'operations/offboarding' },
						{ label: 'Billing — Invoice and Collections SOP', slug: 'operations/billing' },
						{ label: 'Contracts — MSA and SOW Templates', slug: 'operations/contracts' },
						{ label: 'Team — Hiring Scorecard', slug: 'operations/hiring-scorecard' },
						{ label: 'Team — 90-day Ramp Plan', slug: 'operations/ramp-plan' },
						{ label: 'Team — Weekly One on Ones', slug: 'operations/weekly-one-on-ones' },
						{ label: 'Team — Capacity Planning', slug: 'operations/capacity-planning' },
						{ label: 'Team — Offshore VA Hiring', slug: 'operations/va-hiring' },
						{ label: 'Team — VA Training and SOP Library', slug: 'operations/va-training-sop-library' },
						{ label: 'Team — Service Delivery Pod Structure', slug: 'operations/service-pod-structure' },
						{ label: 'Operations — Quarterly Planning Rhythm', slug: 'operations/quarterly-planning' },
						{ label: 'Operations — Crisis Communication Plan', slug: 'operations/crisis-comms' },
						{ label: 'Operations — White-label Fulfillment Partners', slug: 'operations/white-label-fulfillment' },
						{ label: 'Leadership — Founder Role Definition', slug: 'operations/owner-role' },
							{ label: 'Process — Writing a New SOP', slug: 'operations/writing-an-sop' },
							{ label: 'Process — Adding Users to Your Wiki Repo', slug: 'operations/add-github-users' },
					],
				},
				{
					label: 'Measurement',
					items: [
						{ label: 'Project Management — ClickUp Setup', slug: 'measurement/clickup-setup' },
						{ label: 'Analytics — GA4 Setup Standard', slug: 'measurement/ga4-setup' },
						{ label: 'Analytics — GTM Implementation', slug: 'measurement/gtm-implementation' },
						{ label: 'Analytics — Conversion Tracking Audit', slug: 'measurement/conversion-audit' },
						{ label: 'Analytics — Server-side Tracking Standard', slug: 'measurement/server-side-tracking' },
						{ label: 'Reporting — Looker Studio Dashboard', slug: 'measurement/looker-studio' },
						{ label: 'Reporting — Client KPI Dashboard Template', slug: 'measurement/client-kpi-dashboard' },
						{ label: 'Reporting — Agency-Owner KPI Dashboard', slug: 'measurement/agency-owner-dashboard' },
					],
				},
				{
					label: 'Creative and Strategy',
					items: [
						{ label: 'Tools — Tech Stack Overview', slug: 'creative-strategy/tech-stack' },
						{ label: 'Creative — Video Ad Production Pipeline', slug: 'creative-strategy/video-production' },
						{ label: 'Creative — Brand Guideline Kit', slug: 'creative-strategy/brand-guidelines' },
						{ label: 'Creative — Landing Page Template Library', slug: 'creative-strategy/landing-page-library' },
						{ label: 'Creative — Case Study Production', slug: 'creative-strategy/case-study-production' },
						{ label: 'Strategy — Ideal Client Profile', slug: 'creative-strategy/icp' },
						{ label: 'Strategy — Positioning and Offer Design', slug: 'creative-strategy/positioning' },
						{ label: 'Strategy — Customer Research Interviews', slug: 'creative-strategy/customer-research' },
						{ label: 'Strategy — Niche Selection Process', slug: 'creative-strategy/niche-selection' },
						{ label: 'Strategy — Service Bundle Design', slug: 'creative-strategy/service-bundle-design' },
						{ label: 'Strategy — Productized Service Scope', slug: 'creative-strategy/productized-scope' },
						{ label: 'Growth — Referral Program Playbook', slug: 'creative-strategy/referral-program' },
					],
				},
				{
					label: 'Client Retention',
					items: [
						{ label: 'Retention — 30-day Onboarding Sequence', slug: 'retention/onboarding-30-day' },
						{ label: 'Retention — Monthly Client Check-in Cadence', slug: 'retention/monthly-checkin' },
						{ label: 'Retention — Database Reactivation Campaign', slug: 'retention/database-reactivation' },
						{ label: 'Retention — Save-the-Account Playbook', slug: 'retention/save-the-account' },
					],
				},
				{
					label: 'AI and Automation',
					items: [
						{ label: 'AI — Client Voice Brain', slug: 'ai-automation/client-voice-brain' },
						{ label: 'AI — AI-Assisted Content Production', slug: 'ai-automation/ai-content-production' },
						{ label: 'AI — AI Agent for Repetitive Tasks', slug: 'ai-automation/ai-repetitive-tasks' },
					],
				},
			],
		}),
	],
});
